config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get :about_me, to: 'static_pages#about_me'
  get :contact, to: 'static_pages#contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about_me
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_nav_bar.slim
nav.navbar.navbar-dark.bg-custom-transparent
  .container
    = link_to 'Mag Tech', root_path, class: 'navbar-brand navbar-brand-custom'
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    #navbarColor02.collapse.navbar-collapse
      ul.navbar-nav.mr-auto
        li.nav-item
          = link_to t(:about_me), about_me_path, class: 'nav-link'
        li class="nav-item"
          = link_to t(:contact), contact_path, class: 'nav-link'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mag Tech Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.3/yeti/bootstrap.min.css" rel="stylesheet" integrity="sha384-MEq8xmFd953gp2FVvLd8DUEvfBjGCzDjem+gmDqfyyWcaxX4BUD7TtSu1EszNTvK" crossorigin="anonymous">
  <body>
    <%= render 'layouts/nav_bar' %>
    <div class="mt-5 mb-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about_me.slim
.container
  .jumbotron.animated.slideInUp
    h1.display-3.animated.fadeIn.delay-1s = t(:about_me)
    p.lead.animated.fadeIn.delay-1s Cool message.

app/views/static_pages/contact.slim
.container
  .jumbotron.animated.slideInUp
    h1.display-3.animated.fadeIn.delay-1s = t(:contact)
    p.lead.animated.fadeIn.delay-1s Cool message.

app/views/static_pages/home.slim
.container
  .jumbotron.jumbotron-custom.animated.slideInUp
    h1.display-3.animated.fadeIn.delay-1s Bienvenido a Mag Tech
    p.lead.animated.fadeIn.delay-1s Soluciones Web

.services
  h1.display-3 Servicios
  .row
    .col-12.col-md-4
      h3 Páginas web
    .col-12.col-md-4
      h3 Aplicaciones en React Native
    .col-12.col-md-4
      h3 Dev Ops

.services
  h1.display-3 Beneficios
  .row
    .col-12.col-md-4
      h3 Diseño Adaptable
    .col-12.col-md-4
      h3 Impulsar su compañía
    .col-12.col-md-4
      h3 Optimización y Rendimiento